

// ⁡⁢⁣⁣Random Islamic NAME(female) GENERATOR⁡ 😎

const Fname = {
    1: [
        { name: "Ala", meaning: "Excellence" },
        { name: "Aminah", meaning: "Trustworthy" },
        { name: "Abidah", meaning: "Worshipper" },
        { name: "Adibah", meaning: "Cultured" },
        { name: "Adilah", meaning: "Just" },
        { name: "Afaf", meaning: "Chastity" },
        { name: "Aisha", meaning: "Alive" },
        { name: "Aliyah", meaning: "Exalted" },
        { name: "Amal", meaning: "Hope" },
        { name: "Amani", meaning: "Wishes" },
        { name: "Aminah", meaning: "Trustworthy" },
        { name: "Amirah", meaning: "Princess" },
        { name: "Anisah", meaning: "Close friend" },
        { name: "Anjum", meaning: "Stars" },
        { name: "Aqilah", meaning: "Wise" },
        { name: "Areej", meaning: "Sweet smell" },
        { name: "Arwa", meaning: "Mountain gazelle" },
        { name: "Asilah", meaning: "Noble" },
        { name: "Asimah", meaning: "Protector" },
        { name: "Asiyah", meaning: "Strong" },
    ],
    2: [
        { name: "Badiah", meaning: "Wonderful" },
        { name: "Badriyah", meaning: "Full moon" },
        { name: "Barakah", meaning: "Blessing" },
        { name: "Bashirah", meaning: "Bringer of good news" },
        { name: "Basimah", meaning: "Smiling" },
        { name: "Basmah", meaning: "Smile" },
        { name: "Bushra", meaning: "Good news" },
        { name: "Buthaynah", meaning: "Of beautiful and tender body" },
    ],
   
    3: [
        { name: "Dariya", meaning: "River" },
        { name: "Deema", meaning: "Rain" },
        { name: "Deena", meaning: "Religious" },
        { name: "Dua", meaning: "Prayer" },
        { name: "Durra", meaning: "Precious pearl" },
        { name: "Durriya", meaning: "Shining" },
    ],
4: [
        { name: "Faida", meaning: "Benefit" },
        { name: "Faiza", meaning: "Victorious" },
        { name: "Farah", meaning: "Joy" },
        { name: "Fareeda", meaning: "Unique" },
        { name: "Farha", meaning: "Happiness" },
        { name: "Farhana", meaning: "Joyful" },
        { name: "Farukh", meaning: "Blessed" },
        { name: "Fateen", meaning: "Clever" },
        { name: "Fateema", meaning: "Chaste" },
        { name: "Fatimah", meaning: "Abstainer" },
        { name: "Fayrooz", meaning: "Turquoise" },
        { name: "Fazila", meaning: "Virtuous" },
        { name: "Feryal", meaning: "Inspirational" },
        { name: "Firdaws", meaning: "Paradise" },
        { name: "Fatima", meaning: "Captivating" },
    ],
    5: [
        { name: "Ghada", meaning: "Grace" },
        { name: "Ghaya", meaning: "Richness" },
    ],

    6: [
        { name: "Habibah", meaning: "Beloved" },
        { name: "Hadeel", meaning: "Mild" },
        { name: "Hadiya", meaning: "Guide to righteousness" },
        { name: "Hadiyya", meaning: "Gift" },
        { name: "Hala", meaning: "Ring around the moon" },
        { name: "Hameeda", meaning: "Praised" },
        { name: "Hamidah", meaning: "Praiseworthy" },
        { name: "Hana", meaning: "Happiness" },
        { name: "Hanan", meaning: "Compassionate" },
        { name: "Hanifah", meaning: "Devout" },
        { name: "Hasanat", meaning: "Good deeds" },
        { name: "Haseena", meaning: "Beautiful" },
        { name: "Hiba", meaning: "Gift" },
        { name: "Hiyam", meaning: "Love" },
        { name: "Huda", meaning: "Guidance" },
        { name: "Husna", meaning: "Beautiful" },
    ],

    7: [
        { name: "Ibtihaj", meaning: "Happiness" },
        { name: "Ibtisam", meaning: "Smiling" },
        { name: "Iffat", meaning: "Chastity" },
        { name: "Ilham", meaning: "Inspiration" },
        { name: "Iman", meaning: "Faith" },
        { name: "Inayat", meaning: "Kindness" },
    ],
    8: [
        { name: "Jameela", meaning: "Beautiful" },
        { name: "Janan", meaning: "Heart" },
        { name: "Jumana", meaning: "Pearl" },
        { name: "Jimima", meaning: "Beloved" },
        { name: "Jaleela", meaning: "Great" },
        { name: "Jawhara", meaning: "Jewel" },
        { name: "Jannah", meaning: "Paradise" },
        { name: "Jawahir", meaning: "Jewels" },
        { name: "Jasmin", meaning: "Jasmine flower" },
        { name: "Jumanah", meaning: "Silver pearl" },
        { name: "Juwairiya", meaning: "Little jewel" },
        { name: "Juwayriya", meaning: "Little jewel" },
        { name: "Jannat", meaning: "Heaven" },
    ],

    9: [
        { name: "Kamila", meaning: "Perfect" },
        { name: "Kareema", meaning: "Generous" },
        { name: "Kawkab", meaning: "Star" },
        { name: "Kawthar", meaning: "Abundance" },
        { name: "Khadeeja", meaning: "First wife of the Prophet Muhammad" },
        { name: "Khaleela", meaning: "Friend" },
        { name: "Khalida", meaning: "Immortal" },
        { name: "Khawlah", meaning: "Female deer" },
        { name: "Khairunnisa", meaning: "Good woman" },
        { name: "Khayriyyah", meaning: "Charitable" },
    ],

    10: [
        { name: "Labeeba", meaning: "Wise" },
        { name: "Lama", meaning: "Dark lips" },
        { name: "Lamees", meaning: "Soft to the touch" },
        { name: "Lamya", meaning: "Dark-lipped" },
        { name: "Lateefa", meaning: "Gentle" },
        { name: "Layla", meaning: "Night" },
        { name: "Lina", meaning: "Tender" },
        { name: "Lubna", meaning: "Storax tree" },
        { name: "Lulu", meaning: "Pearl" },
    ],

   11: [
        { name: "Maha", meaning: "Beautiful eyes" },
        { name: "Mahasin", meaning: "Virtues" },
        { name: "Maisah", meaning: "Walking with pride" },
        { name: "Majeeda", meaning: "Glorious" },
        { name: "Majidah", meaning: "Glorious" },
        { name: "Malikah", meaning: "Queen" },
        { name: "Manal", meaning: "Achievement" },
        { name: "Maram", meaning: "Aspiration" },
        { name: "Mariyyah", meaning: "Purity" },
        { name: "Maryam", meaning: "Mother of Jesus" },
        { name: "Masirah", meaning: "Traveler" },
        { name: "Maysara", meaning: "Ease" },
        { name: "Maymuna", meaning: "Blessed" },
        { name: "Maysoon", meaning: "Beautiful face" },
        { name: "Muhayrah", meaning: "Skilled" },
        { name: "Muhsina", meaning: "Beneficient" },
        { name: "Mujahida", meaning: "Struggler" },
        { name: "Mumina", meaning: "Believer" },
        { name: "Muna", meaning: "Wish" },
        { name: "Munirah", meaning: "Illuminating" },
        { name: "Munyah", meaning: "Desire" },
    ],

    12: [
        { name: "Nabeeha", meaning: "Intelligent" },
        { name: "Nabeela", meaning: "Noble" },
        { name: "Nabiha", meaning: "Noble" },
        { name: "Nahida", meaning: "Elevated" },
        { name: "Nahla", meaning: "Thirst quencher" },
        { name: "Naila", meaning: "Achiever" },
        { name: "Naima", meaning: "Comfort" },
        { name: "Najda", meaning: "Rescue" },
        { name: "Najiha", meaning: "Successful" },
        { name: "Najla", meaning: "Wide-eyed" },
        { name: "Najma", meaning: "Star" },
        { name: "Najwa", meaning: "Whisper" },
        { name: "Nashwa", meaning: "Fragrance" },
        { name: "Nasiha", meaning: "Advisor" },
        { name: "Nasreen", meaning: "Wild rose" },
        { name: "Nawal", meaning: "Gift" },
        { name: "Nima", meaning: "Blessing" },
        { name: "Nishat", meaning: "Pleasure" },
        { name: "Noora", meaning: "Light" },
        { name: "Nuha", meaning: "Intelligent" },
    ],

    13: [
        { name: "Qamar", meaning: "Moon" },
        { name: "Qaseema", meaning: "Beautiful" },
        { name: "Qayima", meaning: "Goodness" },
    ],

    14: [
        { name: "Rabab", meaning: "White cloud" },
        { name: "Rafeeda", meaning: "Friend" },
        { name: "Raghad", meaning: "Delight" },
        { name: "Raheema", meaning: "Merciful" },
        { name: "Raida", meaning: "Pioneer" },
        { name: "Raifa", meaning: "Kind" },
        { name: "Raisa", meaning: "Leader" },
        { name: "Rajwa", meaning: "Hope" },
        { name: "Rana", meaning: "Elegant" },
        { name: "Raneem", meaning: "Beautiful" },
        { name: "Raqiyah", meaning: "Watchful" },
        { name: "Rasha", meaning: "Young gazelle" },
        { name: "Rasheeda", meaning: "Righteous" },
        { name: "Rasima", meaning: "Protector" },
        { name: "Rayhana", meaning: "Sweet-smelling plant" },
        { name: "Rayya", meaning: "Desert" },
        { name: "Raziya", meaning: "Satisfied" },
        { name: "Reema", meaning: "White antelope" },
        { name: "Rizwana", meaning: "Beautiful" },
        { name: "Ruwayda", meaning: "Guiding to the right path" },
    ],
    15: [
        { name: "Saba", meaning: "Morning breeze" },
        { name: "Sabah", meaning: "Morning" },
        { name: "Sabira", meaning: "Patient" },
        { name: "Sadaf", meaning: "Shell" },
        { name: "Safa", meaning: "Clarity" },
        { name: "Safiyyah", meaning: "Pure" },
        { name: "Sahar", meaning: "Dawn" },
        { name: "Sajidah", meaning: "Prostrate" },
        { name: "Sakeena", meaning: "Calm" },
        { name: "Salma", meaning: "Safe" },
        { name: "Salwa", meaning: "Solace" },
        { name: "Samirah", meaning: "Companion in evening talk" },
        { name: "Samiyah", meaning: "Elevated" },
        { name: "Sana", meaning: "Radiance" },
        { name: "Sara", meaning: "Princess" },
        { name: "Sayeeda", meaning: "Leader" },
        { name: "Seema", meaning: "Precious thing" },
        { name: "Sidrah", meaning: "Tree" },
        { name: "Sufiya", meaning: "Wisdom" },
        { name: "Suha", meaning: "Reddish" },
        { name: "Suhayla", meaning: "Sweet" },
        { name: "Sultana", meaning: "Queen" },
        { name: "Sumayyah", meaning: "Pure and unique" },
        { name: "Sundus", meaning: "Fine silk" },
    ],

    16: [
        { name: "Shafea", meaning: "Healed" },
        { name: "Shaheeda", meaning: "Witness" },
        { name: "Shaheera", meaning: "Famous" },
        { name: "Shakira", meaning: "Thankful" },
        { name: "Shameela", meaning: "Complete" },
        { name: "Shameem", meaning: "Fragrant" },
        { name: "Shamma", meaning: "Light" },
        { name: "Shareefa", meaning: "Noble" },
    ],

    17: [
        { name: "Taghreed", meaning: "Chirping" },
        { name: "Tahani", meaning: "Congratulations" },
        { name: "Tameema", meaning: "Perfect" },
        { name: "Tanweer", meaning: "Illumination" },
        { name: "Tawfeeqa", meaning: "Success" },
        { name: "Thana", meaning: "Thankful" },
        { name: "Thurayya", meaning: "Star" },
        { name: "Tooba", meaning: "Good news" },
        { name: "Tasneem", meaning: "Fountain of paradise" },
        { name: "Tasnim", meaning: "Fountain in paradise" },
        { name: "Taliba", meaning: "Seeker" },
        { name: "Tamara", meaning: "Date palm tree" },
        { name: "Talibah", meaning: "Seeker" },
        { name: "Tahira", meaning: "Pure" },
        { name: "Tayyiba", meaning: "Good" },
        { name: "Tanzila", meaning: "Revelation" },
    ],

    18: [
        { name: "Ulfah", meaning: "Friendship" },
        { name: "Uzma", meaning: "Greatness" },
        { name: "Uswa", meaning: "Example" },
        { name: "Umaira", meaning: "Living a long life" },
        { name: "Ulfat", meaning: "Love" },
        { name: "Umnia", meaning: "Gift" },
    ],

    19: [
        { name: "Wadad", meaning: "Love" },
        { name: "Wafa", meaning: "Faithfulness" },
        { name: "Wajida", meaning: "Finder" },
        { name: "Warda", meaning: "Rose" },
        { name: "Waseema", meaning: "Graceful" },
        { name: "Wasima", meaning: "Companion" },
    ],
    20: [
        { name: "Yamama", meaning: "Dove" },
        { name: "Yameena", meaning: "Right and proper" },
        { name: "Yasmeen", meaning: "Jasmine" },
        { name: "Yumna", meaning: "Good fortune" },
        { name: "Yusra", meaning: "Prosperous" },
        { name: "Yesmina", meaning: "Good and noble" },
        { name: "Yasmina", meaning: "Jasmine" },
    ],

    21: [
        { name: "Zafira", meaning: "Victorious" },
        { name: "Zaha", meaning: "Peace" },
        { name: "Zahida", meaning: "Self-denying" },
        { name: "Zahira", meaning: "Brilliant" },
        { name: "Zahra", meaning: "Flower" },
        { name: "Zakiyya", meaning: "Pure" },
        { name: "Zarwa", meaning: "Pure gold" },
        { name: "Zayba", meaning: "Adornment" },
        { name: "Zuha", meaning: "Morning" },
        { name: "Zulaykha", meaning: "Brilliant" },
        { name: "Zimima", meaning: "Elegant" },
    ],
};

  
 
  
const Lname = {

    1: [
        { name: "Abdullah", meaning: "Servant of Allah" },
        { name: "Ahmed", meaning: "Praiseworthy" },
        { name: "Ali", meaning: "Elevated" },
        { name: "Aziz", meaning: "Beloved" },
        { name: "Amir", meaning: "Prince" },
        { name: "Alawi", meaning: "Descendant of Ali" },
        { name: "Amin", meaning: "Trustworthy" },
        { name: "Aref", meaning: "Wise" },
        { name: "Ashraf", meaning: "Honorable" },
        { name: "Abdallah", meaning: "Servant of Allah" },
        { name: "Akhtar", meaning: "Star" },
        { name: "Aqil", meaning: "Wise" },
        { name: "Alavi", meaning: "Of Ali" },
        { name: "Anwar", meaning: "Radiant" },
        { name: "Azeem", meaning: "Great" },
        { name: "Asghar", meaning: "Younger" },
        { name: "Arif", meaning: "Knowledgeable" },
        { name: "Aydin", meaning: "Enlightened" },
        { name: "Abad", meaning: "Eternal" },
        { name: "Abbas", meaning: "Lion" },
        { name: "Abbasi", meaning: "Descendant of Abbas" },
        { name: "Abdalla", meaning: "Servant of Allah" },
        { name: "Abdella", meaning: "Servant of Allah" },
        { name: "Abdelnour", meaning: "Servant of the light" },
        { name: "Abdelrahman", meaning: "Servant of the Merciful" },
        { name: "Abdi", meaning: "Servant" },
        { name: "Abdo", meaning: "Servant" },
        { name: "Abdoo", meaning: "Servant" },
        { name: "Abdou", meaning: "Servant" },
        { name: "Abdul", meaning: "Servant of the" },
        { name: "Abdulla", meaning: "Servant of Allah" },
        { name: "Abed", meaning: "Worshipper" },
        { name: "Abid", meaning: "Worshipper" },
        { name: "Abood", meaning: "Worshipper" },
        { name: "Aboud", meaning: "Worshipper" },
        { name: "Abu", meaning: "Father" },
        { name: "Adel", meaning: "Just" },
        { name: "Afzal", meaning: "Better" },
        { name: "Agha", meaning: "Master" },
        { name: "Ahmad", meaning: "Praiseworthy" },
        { name: "Ahmadi", meaning: "Praiseworthy" },
        { name: "Ahsan", meaning: "Best" },
        { name: "Akbar", meaning: "Great" },
        { name: "Akbari", meaning: "Great" },
        { name: "Akel", meaning: "Wise" },
        { name: "Akhter", meaning: "Star" },
        { name: "Akram", meaning: "Generous" },
        { name: "Alam", meaning: "Flag" },
        { name: "Allam", meaning: "Scholar" },
        { name: "Allee", meaning: "High" },
        { name: "Alli", meaning: "Elevated" },
        { name: "Ally", meaning: "Elevated" },
        { name: "Aly", meaning: "Elevated" },
        { name: "Aman", meaning: "Peace" },
        { name: "Amara", meaning: "Eternal" },
        { name: "Amber", meaning: "Jewel" },
        { name: "Ameen", meaning: "Trustworthy" },
        { name: "Amen", meaning: "Trustworthy" },
        { name: "Amer", meaning: "Prosperous" },
        { name: "Amini", meaning: "Faithful" },
        { name: "Amiri", meaning: "Prince" },
        { name: "Ammar", meaning: "Virtuous" },
        { name: "Ansari", meaning: "Supporter" },
        { name: "Arafat", meaning: "Familiar" },
        { name: "Arshad", meaning: "Righteous" },
        { name: "Asad", meaning: "Lion" },
        { name: "Aslam", meaning: "Safe" },
        { name: "Asmar", meaning: "Brown" },
        { name: "Assad", meaning: "Lion" },
        { name: "Assaf", meaning: "Evening" },
        { name: "Atallah", meaning: "Gift of God" },
        { name: "Attar", meaning: "Perfumer" },
        { name: "Awan", meaning: "Helper" },
        { name: "Ayoob", meaning: "Messenger" },
        { name: "Ayoub", meaning: "Messenger" },
        { name: "Ayub", meaning: "Messenger" },
        { name: "Azad", meaning: "Free" },
        { name: "Azam", meaning: "Great" },
        { name: "Azer", meaning: "Fire" },
        { name: "Azimi", meaning: "Magnificent" },
        { name: "Azizi", meaning: "Beloved" },
        { name: "Azzam", meaning: "Determined" },
        { name: "Azzi", meaning: "Strong" },
    ],
  
  
2: [
    { name: "Bashir", meaning: "Bearer of good news" },
    { name: "Bilal", meaning: "Moisture" },
    { name: "Basammah", meaning: "Smiling" },
    { name: "Baig", meaning: "Commander" },
    { name: "Bukhari", meaning: "From the city of Bukhara" },
    { name: "Basri", meaning: "From Basra" },
    { name: "Bakir", meaning: "First born" },
    { name: "Bahri", meaning: "Of the sea" },
    { name: "Babar", meaning: "Lion" },
    { name: "Bhati", meaning: "Friendly" },
    { name: "Begum", meaning: "Lady" },
    { name: "Bashar", meaning: "Bringer of good tidings" },
    { name: "Bulbul", meaning: "Nightingale" },
    { name: "Badiah", meaning: "Wonderful" },
    { name: "Badriyah", meaning: "Resembling the full moon" },
    { name: "Barakat", meaning: "Blessings" },
    { name: "Bari", meaning: "Free" },
    { name: "Basha", meaning: "Helper" },
    { name: "Bashara", meaning: "Bringer of good news" },
    { name: "Basher", meaning: "Bringer of good news" },
    { name: "Bashir", meaning: "Bearer of good news" },
    { name: "Baten", meaning: "Strong" },
    { name: "Bacchus", meaning: "Ancient god of wine" },
    { name: "Baccus", meaning: "Ancient god of wine" },
    { name: "Bacho", meaning: "First born" },
    { name: "Baddour", meaning: "Full moon" },
    { name: "Burki", meaning: "Resembling a falcon" },
    { name: "Badour", meaning: "Full moon" },
    { name: "Bagheri", meaning: "Of the tiger" },
    { name: "Bahri", meaning: "Of the sea" },
    { name: "Baig", meaning: "Commander" },
    { name: "Baksh", meaning: "Generous" },
    { name: "Baluch", meaning: "Nomad" },
    { name: "Bangura", meaning: "Buffalo" },
],

3: [
    { name: "Chaudhry", meaning: "Leader" },
    { name: "Chowdhury", meaning: "Leader" },
    { name: "Choudhury", meaning: "Leader" },
    { name: "Can", meaning: "Life" },
    { name: "Chahine", meaning: "Good" },
],

4: [
    { name: "Dwan", meaning: "Dark" },
    { name: "Dada", meaning: "Elder" },
    { name: "Dajani", meaning: "From a noble family" },
    { name: "Dallal", meaning: "Broker" },
    { name: "Daoud", meaning: "Beloved" },
    { name: "Dar", meaning: "Pearl" },
    { name: "Darwish", meaning: "Dervish" },
    { name: "Dawood", meaning: "Beloved" },
    { name: "Diab", meaning: "Wolf" },
    { name: "Dib", meaning: "Bear" },
    { name: "Din", meaning: "Religion" },
    { name: "Doud", meaning: "Beloved" },
],

    5: [
        { name: "Ebrahim", meaning: "Father of many nations" },
        { name: "Ebrahimi", meaning: "Descendant of Abraham" },
        { name: "Edris", meaning: "To teach or learn" },
        { name: "Eid", meaning: "Festival or celebration" },
        { name: "El-Sayed", meaning: "The master" },
        { name: "Elamin", meaning: "Trustworthy" },
        { name: "Elbaz", meaning: "Falcon" },
        { name: "Emami", meaning: "Leader" },
        { name: "Fadel", meaning: "Virtuous" },
        { name: "Fahmy", meaning: "Understanding" },
        { name: "Fahs", meaning: "Lion" },
        { name: "Farag", meaning: "Charming" },
        { name: "Farah", meaning: "Joy" },
        { name: "Faraj", meaning: "Relief" },
        { name: "Fares", meaning: "Knight" },
        { name: "Farha", meaning: "Joy" },
        { name: "Farhat", meaning: "Happiness" },
        { name: "Farid", meaning: "Unique" },
        { name: "Faris", meaning: "Knight" },
        { name: "Farman", meaning: "Decree" },
        { name: "Farooq", meaning: "One who can differentiate between right and wrong" },
        { name: "Farooqui", meaning: "Judge" },
        { name: "Farra", meaning: "Butterfly" },
        { name: "Farrah", meaning: "Joy" },
        { name: "Farran", meaning: "Joyful" },
        { name: "Fawaz", meaning: "Winner" },
        { name: "Fayad", meaning: "Generous" },
        { name: "Firman", meaning: "Order" },
    ],

    6: [
        { name: "Gaber", meaning: "Consoler" },
        { name: "Gad", meaning: "Luck" },
        { name: "Galla", meaning: "Stranger" },
        { name: "Ghaffari", meaning: "Supporter" },
        { name: "Ghanem", meaning: "Successful" },
        { name: "Ghani", meaning: "Wealthy" },
        { name: "Ghattas", meaning: "Gift" },
        { name: "Ghazal", meaning: "Gazelle" },
        { name: "Ghazi", meaning: "Warrior" },
        { name: "Greiss", meaning: "Handsome" },
        { name: "Guler", meaning: "Smiling" },
    ],

    7: [
        { name: "Habeeb", meaning: "Beloved" },
        { name: "Habib", meaning: "Beloved" },
        { name: "Habibi", meaning: "My beloved" },
        { name: "Hadi", meaning: "Guide" },
        { name: "Hafeez", meaning: "Protector" },
        { name: "Hai", meaning: "Alive" },
        { name: "Haidar", meaning: "Lion" },
        { name: "Haider", meaning: "Lion" },
        { name: "Hakeem", meaning: "Wise" },
        { name: "Hakim", meaning: "Wise" },
        { name: "Halaby", meaning: "From Aleppo, Syria" },
        { name: "Halim", meaning: "Patient" },
        { name: "Hallal", meaning: "Sweet" },
        { name: "Hamad", meaning: "Praise" },
        { name: "Hamady", meaning: "Praise" },
        { name: "Hamdan", meaning: "Praiseworthy" },
        { name: "Hamed", meaning: "Praiseworthy" },
        { name: "Hameed", meaning: "Praiseworthy" },
        { name: "Hamid", meaning: "Praiseworthy" },
        { name: "Hamidi", meaning: "Praiseworthy" },
        { name: "Hammad", meaning: "Praiseworthy" },
        { name: "Hammoud", meaning: "Praiseworthy" },
        { name: "Hana", meaning: "Happiness" },
        { name: "Hanif", meaning: "True believer" },
        { name: "Hannan", meaning: "Compassionate" },
        { name: "Haq", meaning: "True" },
        { name: "Haque", meaning: "Justice" },
        { name: "Hares", meaning: "Guardian" },
        { name: "Hariri", meaning: "Silk merchant" },
        { name: "Harron", meaning: "Lively" },
        { name: "Harroun", meaning: "Aaron" },
        { name: "Hasan", meaning: "Handsome" },
        { name: "Hasen", meaning: "Handsome" },
        { name: "Hashem", meaning: "Generous" },
        { name: "Hashemi", meaning: "From Hashemite lineage" },
        { name: "Hashim", meaning: "Crusher" },
        { name: "Hashmi", meaning: "From Hashemite lineage" },
        { name: "Hassan", meaning: "Handsome" },
        { name: "Hassan", meaning: "Good" },
        { name: "Hassen", meaning: "Handsome" },
        { name: "Hatem", meaning: "Judge" },
        { name: "Hoda", meaning: "Guidance" },
        { name: "Hoque", meaning: "Truthful" },
        { name: "Hosein", meaning: "Leader" },
        { name: "Hossain", meaning: "Handsome" },
        { name: "Hosseini", meaning: "From Hossein" },
        { name: "Huda", meaning: "Guidance" },
        { name: "Huq", meaning: "Truth" },
        { name: "Husain", meaning: "Handsome" },
        { name: "Hussain", meaning: "Handsome" },
        { name: "Hussein", meaning: "Handsome" },
    ],
    8: [
        { name: "Ibrahim", meaning: "Father of many nations" },
        { name: "Idris", meaning: "Interpreter" },
        { name: "Imam", meaning: "Religious leader" },
        { name: "Iman", meaning: "Faith" },
        { name: "Iqbal", meaning: "Prosperity" },
        { name: "Irani", meaning: "From Iran" },
        { name: "Ishak", meaning: "Laughter" },
        { name: "Ishmael", meaning: "God hears" },
        { name: "Islam", meaning: "Submission to God" },
        { name: "Ismael", meaning: "God hears" },
        { name: "Ismail", meaning: "God hears" },
    ],

    9: [
        { name: "Jabara", meaning: "Brave" },
        { name: "Jabbar", meaning: "Mighty" },
        { name: "Jabbour", meaning: "Mighty" },
        { name: "Jaber", meaning: "Comforter" },
        { name: "Jabour", meaning: "Comforter" },
        { name: "Jafari", meaning: "Stream" },
        { name: "Jaffer", meaning: "Stream" },
        { name: "Jafri", meaning: "From the tribe of Jafar" },
        { name: "Jalali", meaning: "Majestic" },
        { name: "Jalil", meaning: "Great" },
        { name: "Jama", meaning: "Unity" },
        { name: "Jamail", meaning: "Beautiful" },
        { name: "Jamal", meaning: "Beauty" },
        { name: "Jamil", meaning: "Beautiful" },
        { name: "Jan", meaning: "Life" },
        { name: "Javed", meaning: "Eternal" },
    ],

    10: [
        { name: "Kaba", meaning: "Cube-shaped building in Mecca" },
        { name: "Kaber", meaning: "Great" },
        { name: "Kabir", meaning: "Great" },
        { name: "Kader", meaning: "Powerful" },
        { name: "Kaiser", meaning: "Emperor" },
        { name: "Kaleel", meaning: "Good friend" },
        { name: "Kalil", meaning: "Beloved" },
        { name: "Kamal", meaning: "Perfection" },
        { name: "Kamali", meaning: "Perfection" },
        { name: "Kamara", meaning: "Born during Ramadan" },
        { name: "Kamel", meaning: "Perfect" },
        { name: "Kanan", meaning: "Gardener" },
        { name: "Karam", meaning: "Generosity" },
        { name: "Karim", meaning: "Generous" },
        { name: "Karimi", meaning: "Generous" },
        { name: "Kassem", meaning: "Divider" },
        { name: "Kazemi", meaning: "From Kazem" },
        { name: "Kazi", meaning: "Judge" },
        { name: "Kazmi", meaning: "From Kazem" },
        { name: "Khalaf", meaning: "Successor" },
        { name: "Khalid", meaning: "Eternal" },
        { name: "Khalifa", meaning: "Successor" },
        { name: "Khalil", meaning: "Friend" },
        { name: "Khalili", meaning: "My friend" },
        { name: "Khan", meaning: "Ruler" },
        { name: "Khatib", meaning: "Preacher" },
        { name: "Khawaja", meaning: "Master" },
        { name: "Koroma", meaning: "Descendant of Koroma" },
    ],

    11: [
        { name: "Laham", meaning: "Steel" },
        { name: "Latif", meaning: "Gentle" },
        { name: "Lodi", meaning: "From Lodi" },
        { name: "Lone", meaning: "Lion" },
    ],

    12: [
        { name: "Madani", meaning: "Urban" },
        { name: "Mady", meaning: "Mighty" },
        { name: "Mahdavi", meaning: "Guided" },
        { name: "Mahdi", meaning: "Guided" },
        { name: "Mahfouz", meaning: "Protected" },
        { name: "Mahmood", meaning: "Praised" },
        { name: "Mahmoud", meaning: "Praised" },
        { name: "Mahmud", meaning: "Praised" },
        { name: "Majeed", meaning: "Noble" },
        { name: "Majid", meaning: "Glorious" },
        { name: "Malak", meaning: "Angel" },
        { name: "Malek", meaning: "King" },
        { name: "Malik", meaning: "King" },
        { name: "Mannan", meaning: "Benefactor" },
        { name: "Mansoor", meaning: "Victorious" },
        { name: "Mansour", meaning: "Victorious" },
        { name: "Mansouri", meaning: "From Mansoura" },
        { name: "Mansur", meaning: "Victorious" },
        { name: "Maroun", meaning: "Bitter" },
        { name: "Masood", meaning: "Prosperous" },
        { name: "Masri", meaning: "Egyptian" },
        { name: "Massoud", meaning: "Fortunate" },
        { name: "Matar", meaning: "Rain" },
        { name: "Matin", meaning: "Strong" },
        { name: "Mattar", meaning: "Rain" },
        { name: "Mattar", meaning: "Rain" },
        { name: "Meer", meaning: "Chief" },
        { name: "Meskin", meaning: "Poor" },
        { name: "Miah", meaning: "Eminent" },
        { name: "Mian", meaning: "Honorable" },
        { name: "Mina", meaning: "Harbour" },
        { name: "Minhas", meaning: "Influential" },
        { name: "Mir", meaning: "Prince" },
        { name: "Mirza", meaning: "Prince" },
        { name: "Mitri", meaning: "From Mithra" },
        { name: "Moghaddam", meaning: "Leader" },
    ],
    13: [
        { name: "Mohamad", meaning: "Praiseworthy" },
        { name: "Mohamed", meaning: "Praiseworthy" },
        { name: "Mohammad", meaning: "Praiseworthy" },
        { name: "Mohammadi", meaning: "Praiseworthy" },
        { name: "Mohammed", meaning: "Praiseworthy" },
        { name: "Mohiuddin", meaning: "Enlightened by religion" },
        { name: "Molla", meaning: "Scholar" },
        { name: "Momin", meaning: "Faithful" },
        { name: "Mona", meaning: "Wish" },
        { name: "Morad", meaning: "Desired" },
        { name: "Moradi", meaning: "Wishful" },
        { name: "Mostafa", meaning: "Chosen" },
        { name: "Mourad", meaning: "Wishful" },
        { name: "Mousa", meaning: "Drawn out of the water" },
        { name: "Moussa", meaning: "Drawn out of the water" },
        { name: "Moustafa", meaning: "Chosen" },
        { name: "Mowad", meaning: "Present" },
        { name: "Muhammad", meaning: "Praiseworthy" },
        { name: "Muhammed", meaning: "Praiseworthy" },
        { name: "Munir", meaning: "Bright" },
        { name: "Murad", meaning: "Desired" },
        { name: "Musa", meaning: "Drawn out of the water" },
        { name: "Mussa", meaning: "Drawn out of the water" },
        { name: "Mustafa", meaning: "Chosen" },
    ],

    14: [
        { name: "Naderi", meaning: "Rare" },
        { name: "Nagi", meaning: "Variant of Najib, noble" },
        { name: "Naim", meaning: "Comfort" },
        { name: "Naqvi", meaning: "Leader" },
        { name: "Nasir", meaning: "Supporter" },
        { name: "Nasr", meaning: "Victory" },
        { name: "Nasrallah", meaning: "Help of Allah" },
        { name: "Nasser", meaning: "Victorious" },
        { name: "Nassif", meaning: "Just" },
        { name: "Nawaz", meaning: "Kindness" },
        { name: "Nazar", meaning: "Sight" },
        { name: "Nazir", meaning: "Observer" },
        { name: "Neman", meaning: "Beloved" },
        { name: "Niazi", meaning: "Proud" },
        { name: "Noor", meaning: "Light" },
        { name: "Noorani", meaning: "Light" },
        { name: "Noori", meaning: "Light" },
        { name: "Nour", meaning: "Light" },
        { name: "Nouri", meaning: "Light" },
    ],

    15: [
        { name: "Obeid", meaning: "Servant" },
        { name: "Odeh", meaning: "To praise" },
        { name: "Omar", meaning: "Long-lived" },
        { name: "Omer", meaning: "Long-lived" },
        { name: "Othman", meaning: "Bustard" },
        { name: "Ozer", meaning: "Courageous" },
    ],

    16: [
        { name: "Parsa", meaning: "Pious" },
        { name: "Pasha", meaning: "Lord" },
        { name: "Pashia", meaning: "Lord" },
        { name: "Pirani", meaning: "Descendant of a saint" },
        { name: "Popal", meaning: "Peacock" },
        { name: "Pour", meaning: "Son of" },
    ],

    17: [
        { name: "Qadir", meaning: "Able" },
        { name: "Qasim", meaning: "Divider" },
        { name: "Qazi", meaning: "Judge" },
        { name: "Quadri", meaning: "Able" },
        { name: "Raad", meaning: "Thunder" },
        { name: "Rabbani", meaning: "Divine" },
        { name: "Rad", meaning: "Satisfied" },
        { name: "Radi", meaning: "Happy" },
        { name: "Radwan", meaning: "Pleased" },
        { name: "Rafiq", meaning: "Friend" },
        { name: "Rahaim", meaning: "Kind" },
        { name: "Rahaman", meaning: "Merciful" },
        { name: "Rahim", meaning: "Merciful" },
        { name: "Rahimi", meaning: "Merciful" },
        { name: "Rahman", meaning: "Merciful" },
        { name: "Rahmani", meaning: "Merciful" },
        { name: "Rais", meaning: "Leader" },
        { name: "Ramadan", meaning: "Ninth month of the Islamic calendar" },
        { name: "Ramin", meaning: "God's beloved" },
        { name: "Rashed", meaning: "Guide" },
        { name: "Rasheed", meaning: "Wise" },
        { name: "Rashid", meaning: "Rightly guided" },
        { name: "Rassi", meaning: "Noble" },
        { name: "Rasul", meaning: "Messenger" },
        { name: "Rauf", meaning: "Kind" },
        { name: "Rayes", meaning: "Leader" },
        { name: "Rehman", meaning: "Merciful" },
        { name: "Rehmann", meaning: "Merciful" },
        { name: "Reza", meaning: "Satisfaction" },
        { name: "Riaz", meaning: "Garden" },
        { name: "Rizk", meaning: "Provision" },
    ],
    18: [
        { name: "Saab", meaning: "Forgiveness" },
        { name: "Saad", meaning: "Felicity" },
        { name: "Saade", meaning: "Fortune" },
        { name: "Saadeh", meaning: "Fortunate" },
        { name: "Saah", meaning: "Rest" },
        { name: "Saba", meaning: "Morning" },
        { name: "Saber", meaning: "Patient" },
        { name: "Sabet", meaning: "Firm" },
        { name: "Sabir", meaning: "Patient" },
        { name: "Sadek", meaning: "Sincere" },
        { name: "Sader", meaning: "Serious" },
        { name: "Sadiq", meaning: "Truthful" },
        { name: "Sadri", meaning: "Chest" },
        { name: "Saeed", meaning: "Happy" },
        { name: "Safar", meaning: "Traveler" },
        { name: "Safi", meaning: "Pure" },
        { name: "Sahli", meaning: "Easygoing" },
        { name: "Saidi", meaning: "Happy" },
        { name: "Sala", meaning: "Peace" },
        { name: "Salaam", meaning: "Peace" },
        { name: "Saladin", meaning: "Righteousness of religion" },
        { name: "Salah", meaning: "Righteousness" },
        { name: "Salahuddin", meaning: "Righteousness of religion" },
        { name: "Salam", meaning: "Peace" },
        { name: "Salama", meaning: "Peace" },
        { name: "Salame", meaning: "Peace" },
        { name: "Salameh", meaning: "Peaceful" },
        { name: "Saleem", meaning: "Safe" },
        { name: "Saleh", meaning: "Good" },
        { name: "Salehi", meaning: "Good" },
        { name: "Salek", meaning: "Good" },
        { name: "Salem", meaning: "Safe" },
        { name: "Salih", meaning: "Good" },
        { name: "Salik", meaning: "Good" },
        { name: "Salim", meaning: "Safe" },
        { name: "Salloum", meaning: "Peaceful" },
        { name: "Salman", meaning: "Safe" },
        { name: "Samaan", meaning: "Like sky" },
        { name: "Samad", meaning: "Eternal" },
        { name: "Samara", meaning: "Fruitful" },
        { name: "Sami", meaning: "Elevated" },
        { name: "Samra", meaning: "Fruitful" },
        { name: "Sani", meaning: "Brilliant" },
        { name: "Sarah", meaning: "Princess" },
        { name: "Sarwar", meaning: "Leader" },
        { name: "Sattar", meaning: "Concealer" },
        { name: "Satter", meaning: "Shield" },
        { name: "Sawaya", meaning: "Carpenter" },
        { name: "Sayed", meaning: "Chief" },
        { name: "Selim", meaning: "Safe" },
        { name: "Semaan", meaning: "Listener" },
        { name: "Sesay", meaning: "Destroyer" },
        { name: "Shaban", meaning: "Eighth month of Islamic calendar" },
        { name: "Shabazz", meaning: "Youthful" },
        { name: "Shad", meaning: "Happy" },
        { name: "Shaer", meaning: "Poet" },
        { name: "Shafi", meaning: "Healer" },
        { name: "Shah", meaning: "King" },
        { name: "Shahan", meaning: "King" },
        { name: "Shaheed", meaning: "Martyr" },
        { name: "Shaheen", meaning: "Eagle" },
        { name: "Shahid", meaning: "Witness" },
        { name: "Shahidi", meaning: "Witness" },
        { name: "Shahin", meaning: "Royal" },
        { name: "Shaikh", meaning: "Elder" },
        { name: "Shaker", meaning: "Thankful" },
        { name: "Shakir", meaning: "Thankful" },
        { name: "Shakoor", meaning: "Thankful" },
        { name: "Sham", meaning: "Evening" },
        { name: "Shams", meaning: "Sun" },
        { name: "Sharaf", meaning: "Honor" },
        { name: "Shareef", meaning: "Noble" },
        { name: "Sharif", meaning: "Noble" },
        { name: "Shariff", meaning: "Noble" },
        { name: "Sharifi", meaning: "Noble" },
        { name: "Shehadeh", meaning: "Young" },
        { name: "Shehata", meaning: "Joyful" },
        { name: "Sheikh", meaning: "Elder" },
        { name: "Siddiqi", meaning: "Truthful" },
        { name: "Siddique", meaning: "Truthful" },
        { name: "Siddiqui", meaning: "Truthful" },
        { name: "Sinai", meaning: "Spearhead" },
        { name: "Soliman", meaning: "Peaceful" },
        { name: "Soltani", meaning: "Of the Sultan" },
        { name: "Srour", meaning: "Happiness" },
        { name: "Sulaiman", meaning: "Peaceful" },
        { name: "Suleiman", meaning: "Peaceful" },
        { name: "Sultan", meaning: "Sovereign" },
        { name: "Sultana", meaning: "Queen" },
        { name: "Syed", meaning: "Noble" },
    ],

    19: [
        { name: "Tabatabai", meaning: "Of the generous" },
        { name: "Tabet", meaning: "Pure" },
        { name: "Taha", meaning: "Pure" },
        { name: "Taheri", meaning: "Pure" },
        { name: "Tahir", meaning: "Pure" },
        { name: "Tamer", meaning: "Date palm" },
        { name: "Tariq", meaning: "Morning star" },
        { name: "Tawil", meaning: "Tall" },
        { name: "Turay", meaning: "Brave" },
    ],

    20: [
        { name: "Uddin", meaning: "Faith" },
        { name: "Ullah", meaning: "Allah" },
        { name: "Usman", meaning: "Trustworthy" },
        { name: "Vaziri", meaning: "Ministerial" },
        { name: "Vohra", meaning: "Leader" },
    ],

    21: [
        { name: "Wahab", meaning: "Generous" },
        { name: "Wahba", meaning: "Generous" },
        { name: "Waheed", meaning: "Unique" },
        { name: "Wakim", meaning: "Judge" },
        { name: "Wali", meaning: "Guardian" },
    ],

    22: [
        { name: "Yacoub", meaning: "Supplanter" },
        { name: "Yamin", meaning: "Right hand" },
        { name: "Yasin", meaning: "One of the prophets" },
        { name: "Yassin", meaning: "One of the prophets" },
        { name: "Younes", meaning: "Jonah" },
        { name: "Younis", meaning: "Jonah" },
        { name: "Yousef", meaning: "God will increase" },
        { name: "Yousif", meaning: "God will increase" },
        { name: "Youssef", meaning: "God will increase" },
        { name: "Yousuf", meaning: "God will increase" },
    ],

    23: [
        { name: "Zadeh", meaning: "Son of" },
        { name: "Zafar", meaning: "Victory" },
        { name: "Zaher", meaning: "Bright" },
        { name: "Zahra", meaning: "Flower" },
        { name: "Zaidi", meaning: "Abundance" },
        { name: "Zakaria", meaning: "Remembered by God" },
        { name: "Zaki", meaning: "Pure" },
    ],
};


function generateName() {
    const nameElement = document.getElementById("rname"); // Define nameElement
    const meaningsElement = document.getElementById("meaning"); // Define nameElement
    const RandomTerm = (obj) => {
        const keys = Object.keys(obj);
        const randomKey = keys[Math.floor(Math.random() * keys.length)];
        const randomIndex = Math.floor(Math.random() * obj[randomKey].length);
        return obj[randomKey][randomIndex];
    };

    const FName = RandomTerm(Fname);
    const LName = RandomTerm(Lname);

    const genName = `🎉 <p style="margin-top:1rem">  ${FName.name} ${LName.name} </p> `;
    const genMeanings = `${FName.name} means ${FName.meaning} and ${LName.name} means ${LName.meaning}`;
    
    nameElement.innerHTML = genName;
    meaningsElement.textContent = genMeanings;
    nameElement.style.opacity = 1;
    nameElement.style.transform = "translateY(-20%)"; // Initial position off-screen to the left

    // Apply animation by gradually moving the name from left to right
    nameElement.animate([
        { transform: "translateY(-20%)", opacity: 0 }, // Start position and opacity
        { transform: "translateY(0)", opacity: 1 } // End position and opacity
    ], {
        duration: 1000, // Animation duration in milliseconds
        easing: "ease-out" // Easing function
    });
}
